apiVersion: v1
kind: Service
metadata:
  annotations:
    tier: backend
  name: redis-master
  namespace: team2
  labels:
    app: redis
    role: master
    tier: backend
spec:
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379
  selector:
    app: redis
    role: master
    tier: backend
